config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root to: 'welcome#index'

    get '/' => 'welcome#index'
    get '/volunteers/login' => 'volunteer_sessions#new'
    post '/volunteers/login' => 'volunteer_sessions#create', as: 'create_volunteer_session'
    delete '/volunteers/logout' => 'volunteer_sessions#destroy', as: 'destroy_volunteer_sessions'

    get '/care_groups/login' => 'care_group_sessions#new'
    post '/care_groups/login' => 'care_group_sessions#create'
    delete '/care_groups/logout' => 'care_group_sessions#destroy', as: 'destroy_care_group_sessions'

    # These routes will be for signup. The first renders a form in the browse, the second will
    # receive the form and create a user in our database using the data given to us by the user.
    get '/volunteers/signup' => 'volunteers#new'
    post '/volunteers' => 'volunteers#create'

    get '/care_groups/signup' => 'care_groups#new'
    post '/care_groups' => 'care_groups#create'

    # end of signup and login routes

    # volunteer routes

    get '/volunteers/:id', to: 'volunteers#show', as: 'volunteer'
    get '/volunteers/:id/edit', to: 'volunteers#edit', as: 'edit_volunteer'
    patch '/volunteers/:id', to: 'volunteers#update', as: 'update_volunteer'

    # caregroup routes
    get '/care_groups', to: 'care_groups#index', as: 'all_care_groups'
    get '/care_groups/:id', to: 'care_groups#show', as: 'care_group'
    get '/care_groups/:id/edit', to: 'care_groups#edit', as: 'edit_care_group'
    patch '/care_groups/:id', to: 'care_groups#update'

    # senior routes

    get '/care_groups/:care_group_id/seniors/new', to: 'seniors#new', as: 'new_care_group_senior'
    get '/care_groups/:care_group_id/seniors', to: 'care_groups#show_seniors', as: 'all_care_group_seniors'
    post '/care_groups/:care_group_id/seniors', to: 'seniors#create'
    get '/care_groups/:care_group_id/seniors/:id', to: 'seniors#show', as: 'care_group_senior'
    get '/care_groups/:care_group_id/seniors/:id/edit', to: 'seniors#edit', as: 'edit_care_group_senior'
    patch '/care_groups/:care_group_id/seniors/:id', to: 'seniors#update'
    delete '/care_groups/:care_group_id/seniors/:id', to: 'seniors#destroy', as: 'delete_care_group_senior'

    # visit routes

    delete '/seniors/:senior_id/visits/:id', to: 'visits#destroy', as: 'delete_visit'
    post '/seniors/:senior_id/visits', to: 'visits#create', as: 'new_senior_visit'
    get '/seniors/:senior_id/visits/:id', to: 'visits#show', as: 'senior_visit'
    put '/seniors/:senior_id/visits/:id', to: 'visits#approve', as: 'approve_visit'
    patch '/seniors/:senior_id/visits/:id', to: 'visits#complete', as: 'complete_visit'
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
    has_attached_file :avatar, styles: { medium: '200x200>', thumb: '100x100>' }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: /@/
    validates :password, length: { minimum: 6 }, on: :create

    has_many :visits, dependent: :destroy
    has_many :seniors, through: :visits

    has_secure_password
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
    def new
        @volunteer = Volunteer.new
    end

    def create
        @volunteer = Volunteer.new(volunteer_params)
        if @volunteer.save
            flash[:notice] = 'Welcome to the Welcom Wisdom Site!'
            VolunteerMailer.welcome_email(@volunteer).deliver_now
            session[:volunteer_id] = @volunteer.id
            redirect_to '/volunteers/login'
        else
            flash[:notice] =
                @volunteer.errors.full_messages.join(', ')
            redirect_to '/volunteers/signup'
        end
    end

    def show
        @volunteer = Volunteer.find_by_id(params[:id])
    end

    def edit
        @volunteer = current_volunteer
    end

    def update
        @volunteer = Volunteer.find_by_id(params[:id])
        if @volunteer.update_attributes(volunteer_params)
            flash[:notice] = 'Your profile information has been updated.'
            redirect_to volunteer_path(@volunteer)
        else
            render 'edit'
        end
    end

    private

    def volunteer_params
        params.require(:volunteer).permit(:name, :email, :password, :password_confirmation, :avatar, :about, :location, :contact)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 center-align">
            <h2>Update!</h2>
        </div>
    </div>
</div>
<div class="container">
    <div class="row center-align">
        <%= form_for @volunteer, url: "/volunteers/#{@volunteer.id}", html: { multipart: true, class: "col s12 m6 offset-m3"}, method: :patch do |f| %>
        <b>Name:
        </b><%= f.text_field :name, required: true %>
        <b>Profile Photo:
        </b><br><%= f.file_field :avatar %><br>
        <b>About:
        </b><%= f.text_area :about %>
        <b>Location:
        </b><%= f.text_area :location %>
        <b>Contact:
        </b><%= f.text_area :contact %>
        <%= f.submit 'Update', class: 'btn waves-effect waves-light' %>
        <% end %>
    </div>
</div>
</div>

app/views/volunteers/index.html.erb
all volunteers

app/views/volunteers/new.html.haml
.container.center-align
  .row
    .col-s12-m6.offset-m3
      %br
      %h2 Sign up as Volunteer!
      %br
      .col-md-12.text-danger
        = flash[:error]

        = form_for :volunteer, url: '/volunteers' do |f|
          .form-group
            = f.text_field :name, class: "form-control", placeholder: "Name"
          .form-group
            = f.text_field :email, class: "form-control", placeholder: "Email"
          .form-group
            = f.password_field :password, class: "form-control", placeholder: "Password"
          .form-group
            = f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password"
            = f.hidden_field :avatar, :value => "http://i.imgur.com/9JlhmGx.png"
          .form-group
            %br
            = f.submit "Sign Up", class: "btn btn-success"

app/views/volunteers/show.html.erb
<div class="row col s12" style="margin-top: 35px;">
    <div class="col s5">
        <div class="container">
            <div class="card orange lighten-2">
                <div class="card-content white-text">
                    <h2 class="center-align" style="margin-top: 0;"><%= @volunteer.name %></h2>
                    <div class="row center-align">
                        <div class="container profile_image center-align">
                            <img src="<%= @volunteer.avatar.url%>" style="width: 200px; height: 200px;">
                        </div>
                    </div>
                </div>
                <div class="row center-align" style="padding-bottom: 20px;">
                    <div class='container'>
                        <span class="white-text">
                            About: <%= @volunteer.about %>
                            <br>
                            Location: <%= @volunteer.location %>
                        </span>
                        <br>
                        <br>
                        <%= link_to "Edit Profile", edit_volunteer_path(@volunteer), class: "waves-effect waves-light btn center-align" %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <% if @current_care_group == nil %>
    <div class="col s7">
        <h4>My Pending Visit Requests</h4>
        <div class="row">
            <% @volunteer.visits.each do |visit| %>
            <% if visit.pending? %>
            <div class="col s12 m10">
                <div class="card white">
                    <div class="card-content white-text center-align">
                        <span class="card-title">
                            <%= link_to visit.senior.name, care_group_senior_path(visit.senior) %></span>
                        <div class="center-align">
                            <%= link_to "Cancel This Request",  delete_visit_path({senior_id: visit.senior, id: visit}), method: :delete, class: "waves-effect waves-light orange lighten-1 btn" %>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <% end %>
        </div>
    </div>
    <% end %>
</div>