config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root to: 'welcome#index'

    get '/' => 'welcome#index'
    get '/volunteers/login' => 'volunteer_sessions#new'
    post '/volunteers/login' => 'volunteer_sessions#create', as: 'create_volunteer_session'
    delete '/volunteers/logout' => 'volunteer_sessions#destroy', as: 'destroy_volunteer_sessions'

    get '/care_groups/login' => 'care_group_sessions#new'
    post '/care_groups/login' => 'care_group_sessions#create'
    delete '/care_groups/logout' => 'care_group_sessions#destroy', as: 'destroy_care_group_sessions'

    # These routes will be for signup. The first renders a form in the browse, the second will
    # receive the form and create a user in our database using the data given to us by the user.
    get '/volunteers/signup' => 'volunteers#new'
    post '/volunteers' => 'volunteers#create'

    get '/care_groups/signup' => 'care_groups#new'
    post '/care_groups' => 'care_groups#create'

    # end of signup and login routes

    # volunteer routes

    get '/volunteers/:id', to: 'volunteers#show', as: 'volunteer'
    get '/volunteers/:id/edit', to: 'volunteers#edit', as: 'edit_volunteer'
    patch '/volunteers/:id', to: 'volunteers#update', as: 'update_volunteer'

    # caregroup routes
    get '/care_groups', to: 'care_groups#index', as: 'all_care_groups'
    get '/care_groups/:id', to: 'care_groups#show', as: 'care_group'
    get '/care_groups/:id/edit', to: 'care_groups#edit', as: 'edit_care_group'
    patch '/care_groups/:id', to: 'care_groups#update'

    # senior routes

    get '/care_groups/:care_group_id/seniors/new', to: 'seniors#new', as: 'new_care_group_senior'
    get '/care_groups/:care_group_id/seniors', to: 'care_groups#show_seniors', as: 'all_care_group_seniors'
    post '/care_groups/:care_group_id/seniors', to: 'seniors#create'
    get '/care_groups/:care_group_id/seniors/:id', to: 'seniors#show', as: 'care_group_senior'
    get '/care_groups/:care_group_id/seniors/:id/edit', to: 'seniors#edit', as: 'edit_care_group_senior'
    patch '/care_groups/:care_group_id/seniors/:id', to: 'seniors#update'
    delete '/care_groups/:care_group_id/seniors/:id', to: 'seniors#destroy', as: 'delete_care_group_senior'

    # visit routes

    delete '/seniors/:senior_id/visits/:id', to: 'visits#destroy', as: 'delete_visit'
    post '/seniors/:senior_id/visits', to: 'visits#create', as: 'new_senior_visit'
    get '/seniors/:senior_id/visits/:id', to: 'visits#show', as: 'senior_visit'
    put '/seniors/:senior_id/visits/:id', to: 'visits#approve', as: 'approve_visit'
    patch '/seniors/:senior_id/visits/:id', to: 'visits#complete', as: 'complete_visit'
end

app/models/care_group.rb
class CareGroup < ApplicationRecord
    has_attached_file :photo, styles: { medium: '200x200>', thumb: '100x100>' }
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: /@/
    validates :password, length: { minimum: 6 }, on: :create

    has_many :seniors, dependent: :destroy

    has_secure_password
end

app/controllers/care_groups_controller.rb
class CareGroupsController < ApplicationController
    def index
        @care_groups = CareGroup.all
    end

    def new; end

    def create
        @care_group = CareGroup.new(care_group_params)
        if @care_group.save
            flash[:notice] = 'Welcome to the Welcom Wisdom Site!'
            session[:care_group_id] = @care_group.id
            redirect_to '/care_groups/login'
        else
            flash[:notice] =
                @care_group.errors.full_messages.join(', ')
            redirect_to '/care_groups/signup'
        end
    end

    def show
        @care_group = CareGroup.find_by_id(params[:id])
    end

    def show_seniors
        @care_group = CareGroup.find_by_id(params[:care_group_id])
    end

    def edit
        @care_group = current_care_group
    end

    def update
        @care_group = CareGroup.find(session[:care_group_id])
        if @care_group.update_attributes(care_group_params)
            flash[:notice] = 'Your profile information has been updated.'
            redirect_to care_group_path(@care_group)
        else
            render 'edit'
        end
    end

    private

    def care_group_params
        params.require(:care_group).permit(:name, :email, :password, :password_confirmation, :photo, :location, :about, :senior_id)
    end
end

app/helpers/care_groups_helper.rb
module CareGroupsHelper
end

app/views/care_groups/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 center-align">
            <h2>Update!</h2>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <%= form_for @care_group, url: "/care_groups/#{@care_group.id}", html: { multipart: true, class: "col s12 m6 offset-m3"}, method: :patch do |f| %>
        <b>Name:
        </b><%= f.text_field :name, required: true %>
        <b>Company Photo:
        </b><%= f.file_field :photo %>
        <b>About:
        </b><%= f.text_area :about %>
        <b>Location:
        </b><%= f.text_area :location %>
        <b>Contact:
        </b><%= f.text_area :contact %>
        <%= f.submit 'Update', class: 'btn waves-effect waves-light' %>
        <% end %>
    </div>
</div>
</div>

app/views/care_groups/index.html.erb
<div class="col m8 center-align container" style="margin-top: 30px;">
    <ul class="collection">
        <% @care_groups.each do |care_group| %>
        <li class="collection-item">
            <span class="care_group_name">
                <h4><%= link_to care_group.name, care_group_path(care_group) %></h4>
            </span>
            <h5>Location: <%= care_group.location %> </h5>
            <br>
        </li>
        <% end %>
    </ul>
</div>

app/views/care_groups/new.html.haml
.container.center-align
  .row
    .col-s12-m6.offset-m3
      %br
      %h2 Sign Up as Care Group
      %br
      .col-md-12.text-danger
        = flash[:error]

        = form_for :care_group, url: '/care_groups' do |f|
          .form-group
            = f.text_field :name, class: "form-control", placeholder: "Name"
          .form-group
            = f.text_field :email, class: "form-control", placeholder: "Email"
            .form-group
              = f.text_field :location, class: "form-control", placeholder: "Location (ex. San Francisco, CA)"
          .form-group
            = f.password_field :password, class: "form-control", placeholder: "Password"
          .form-group
            = f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password"
            = f.hidden_field :photo, :value => "http://i.imgur.com/9JlhmGx.png"
          .form-group
            %br
            = f.submit "Sign Up", class: "btn btn-success"

app/views/care_groups/show.html.erb
<div class="row col s12" style="margin-top: 35px;">
    <div class="col s5">
        <div class="container">
            <div class="card blue-grey lighten-2">
                <div class="card-content white-text">
                    <h2 class="center-align" style="margin-top: 0;"><%= @care_group.name %></h2>
                    <div class="row center-align">
                        <div class="container profile_image center-align">
                            <img src="<%= @care_group.photo.url%>" style="width: 200px; height: 200px;">
                        </div>
                    </div>
                </div>
                    <div class="row center-align" style="padding-bottom: 20px;">
                        <div class='container'>
                            <span class="white-text">
                            About: <%= @care_group.about %>
                            <br>
                            Location: <%= @care_group.location %>
                            </span>
                            <br>
                            <br>
                            <% if current_care_group == @care_group %>
                            <%= link_to "Edit Profile", edit_care_group_path(@care_group), class: "waves-effect waves-light btn center-align" %>
                            <% end %>
                        </div>
                  </div>
              </div>
          </div>
      </div>

    <div class="col s6">
        <div class="container center-align" style="margin-bottom: 40px; margin-top: 20px">
            <%= link_to "View all senior members", all_care_group_seniors_path(@care_group), class: "waves-effect waves-light btn" %>
        </div>

        <% if current_care_group == @care_group %>
        <h4>Pending Visit Requests</h4>
        <div class="row">
            <% @care_group.seniors.each do |senior| %>
            <% senior.visits.each do |visit| %>
            <% if visit.pending? %>
            <div class="col s12 m10">
                <div class="card white">
                    <div class="card-content black-text center-align">
                        <span class="card-title">
                            <%= link_to visit.volunteer.name, volunteer_path(visit.volunteer) %>
                            wants to visit
                            <%= visit.senior.name %>
                        </span>
                        <div class="center-align">
                            <%= link_to "View", senior_visit_path(senior, visit), class: "waves-effect waves-light orange lighten-1 btn" %>
                        </div>

                    </div>
                </div>
            </div>
            <% end %>
            <% end %>
            <% end %>
        </div>

        <hr>

        <h4>Current Visits</h4>

        <table>
            <thead>
                <tr>
                    <th data-field="id">Senior Name</th>
                    <th data-field="name">Volunteer Name</th>
                    <th data-field="price">Status Update</th>
                </tr>
            </thead>
            <% @care_group.seniors.each do |senior| %>
            <% senior.visits.each do |visit| %>
            <% if visit.approved? && visit.visit_complete == false %>
            <tbody>
                <tr>
                    <td><%= visit.senior.name %>
                    </td>
                    <td><%= visit.volunteer.name %>
                    </td>
                    <td><%= button_to "Complete this visit", complete_visit_path({senior_id: visit.senior, id: visit}), method: :patch, class:"btn btn-primary" %></td>
                </tr>
            </tbody>
            <% end %>
            <% end %>
            <% end %>
        </table>
        <% end %>
    </div>
</div>

app/views/care_groups/show_seniors.html.erb
<div class="center-align" style="margin-top: 30px;">
    <%= link_to "Back", care_group_path(params[:care_group_id]), class: "waves-effect waves-light btn" %>
    <% if current_care_group == CareGroup.find(params[:care_group_id]) %>
    <%= link_to "Add a member", new_care_group_senior_path, class: "waves-effect waves-light btn" %>
    <% end %>
</div>

<div class="col m8 container" style="margin-top: 30px;">
    <ul class="collection">
        <% @care_group.seniors.each do |senior| %>
        <li class="collection-item">
            <h5 class="name"><%= link_to senior.name, care_group_senior_path({care_group_id: params[:care_group_id], id: senior}) %></h5>
            <p>Interests:<%= senior.interests %><p>
        </li>
        <% end %>
    </ul>
</div>