config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root to: 'welcome#index'

    get '/' => 'welcome#index'
    get '/volunteers/login' => 'volunteer_sessions#new'
    post '/volunteers/login' => 'volunteer_sessions#create', as: 'create_volunteer_session'
    delete '/volunteers/logout' => 'volunteer_sessions#destroy', as: 'destroy_volunteer_sessions'

    get '/care_groups/login' => 'care_group_sessions#new'
    post '/care_groups/login' => 'care_group_sessions#create'
    delete '/care_groups/logout' => 'care_group_sessions#destroy', as: 'destroy_care_group_sessions'

    # These routes will be for signup. The first renders a form in the browse, the second will
    # receive the form and create a user in our database using the data given to us by the user.
    get '/volunteers/signup' => 'volunteers#new'
    post '/volunteers' => 'volunteers#create'

    get '/care_groups/signup' => 'care_groups#new'
    post '/care_groups' => 'care_groups#create'

    # end of signup and login routes

    # volunteer routes

    get '/volunteers/:id', to: 'volunteers#show', as: 'volunteer'
    get '/volunteers/:id/edit', to: 'volunteers#edit', as: 'edit_volunteer'
    patch '/volunteers/:id', to: 'volunteers#update', as: 'update_volunteer'

    # caregroup routes
    get '/care_groups', to: 'care_groups#index', as: 'all_care_groups'
    get '/care_groups/:id', to: 'care_groups#show', as: 'care_group'
    get '/care_groups/:id/edit', to: 'care_groups#edit', as: 'edit_care_group'
    patch '/care_groups/:id', to: 'care_groups#update'

    # senior routes

    get '/care_groups/:care_group_id/seniors/new', to: 'seniors#new', as: 'new_care_group_senior'
    get '/care_groups/:care_group_id/seniors', to: 'care_groups#show_seniors', as: 'all_care_group_seniors'
    post '/care_groups/:care_group_id/seniors', to: 'seniors#create'
    get '/care_groups/:care_group_id/seniors/:id', to: 'seniors#show', as: 'care_group_senior'
    get '/care_groups/:care_group_id/seniors/:id/edit', to: 'seniors#edit', as: 'edit_care_group_senior'
    patch '/care_groups/:care_group_id/seniors/:id', to: 'seniors#update'
    delete '/care_groups/:care_group_id/seniors/:id', to: 'seniors#destroy', as: 'delete_care_group_senior'

    # visit routes

    delete '/seniors/:senior_id/visits/:id', to: 'visits#destroy', as: 'delete_visit'
    post '/seniors/:senior_id/visits', to: 'visits#create', as: 'new_senior_visit'
    get '/seniors/:senior_id/visits/:id', to: 'visits#show', as: 'senior_visit'
    put '/seniors/:senior_id/visits/:id', to: 'visits#approve', as: 'approve_visit'
    patch '/seniors/:senior_id/visits/:id', to: 'visits#complete', as: 'complete_visit'
end

app/models/senior.rb
class Senior < ApplicationRecord
    has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    belongs_to :care_group
    has_many :visits
    has_many :volunteers, through: :visits
end

app/controllers/seniors_controller.rb
class SeniorsController < ApplicationController
    def new
        @senior = Senior.new
    end

    def create
        @care_group = current_care_group
        @senior = Senior.new(senior_params)
        @senior.care_group_id = current_care_group.id
        if @senior.save
            flash[:notice] = 'You have successfully created a new senior member!'
            redirect_to all_care_group_seniors_path(current_care_group)
        else
            flash[:error] = @senior.errors.full_messages.join(', ')
        end
    end

    def edit
        @senior = Senior.find_by_id(params[:id])
        @care_group = current_care_group
        @current_care_group_id = params[:care_group_id]
    end

    def show
        @volunteer = current_volunteer
        @care_group = current_care_group
        @current_care_group_id = params[:care_group_id]

        @senior = Senior.find_by_id(params[:id])
    end

    def update
        @care_group = current_care_group
        @current_care_group_id = params[:care_group_id]
        @senior = Senior.find_by_id(params[:id])
        if @senior.update_attributes(senior_params)
            flash[:notice] = 'Your member information has been updated.'
            redirect_to all_care_group_seniors_path(@care_group, @senior)
        else
            flash[:notice] =
                @senior.errors.full_messages.join(', ')
            redirect_to edit_care_group_senior_path(@care_group, @senior)
        end
    end

    def destroy
        @care_group = current_care_group
        @current_care_group_id = params[:care_group_id]
        @senior = Senior.find_by_id(params[:id])
        if @senior.destroy
            flash[:notice] = 'Your member has been removed.'
            redirect_to all_care_group_seniors_path(current_care_group)
        end
    end

    private

    def senior_params
        params.require(:senior).permit(:name, :location, :about, :interests, :care_group_id)
   end
end

app/helpers/seniors_helper.rb
module SeniorsHelper
end

app/views/seniors/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 center-align">
            <h2>Update!</h2>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <%= form_for :senior, url: "/care_groups/#{@current_care_group_id}/seniors/#{@senior.id}", html: { multipart: true, class: "col s12 m6 offset-m3"}, method: :patch do |f| %>
        <b>Name:
        </b><%= f.text_field :name, required: true %>
        <b>Interests:
        </b><%= f.text_area :interests %>
        <%= f.submit 'Update', class: 'btn waves-effect waves-light' %>
        <% end %>
    </div>
</div>
</div>

app/views/seniors/index.html.erb
<%= link_to "Back", care_group_path(params[:care_group_id]), class: "waves-effect waves-light btn" %>

<% if current_care_group == CareGroup.find(params[:care_group_id]) %>
<%= link_to "Add a member", new_care_group_senior_path, class: "waves-effect waves-light btn" %>
<% end %>

<div class="row">
            <% @seniors.each do |senior| %>
            <div class="col s12 center-align">
                <h2 class="name"><%= link_to senior.name, care_group_senior_path({care_group_id: params[:care_group_id], id: senior}) %></h2>
                <h5 class="location"><%= senior.location %></h5>
                <h5 class="interests"><%= senior.interests %></h5>

        </div>
        <% end %>
      </div>

app/views/seniors/new.html.haml
.container.center-align
  .row
    .col-s12-m6.offset-m3
      %br
      %h2 New Member Registration
      %br
      .col-md-12.text-danger
        = flash[:error]

        = form_for :senior, url: '/care_groups/:care_group_id/seniors' do |f|
          .form-group
            = f.text_field :name, class: "form-control", placeholder: "Name"
          .form-group
            = f.text_field :location, class: "form-control", placeholder: "Location"
            .form-group
              = f.text_field :interests, class: "form-control", placeholder: "Interests"
              = f.hidden_field :image, :value => "http://i.imgur.com/9JlhmGx.png"
          .form-group
          %br
            = f.submit "Submit", class: "btn btn-success"

app/views/seniors/show.html.erb
<div class="center-align" style="margin-top: 30px;">
    <% if @current_volunteer == nil %>
      <%= link_to "Edit", edit_care_group_senior_path(@senior), class: "waves-effect waves-light btn"  %>
      <%= link_to "Delete", delete_care_group_senior_path, method: :delete, class: "waves-effect waves-light btn" %>
    <% end %>

    <%= link_to "Back", all_care_group_seniors_path, class: "waves-effect waves-light btn" %>

    <% if @current_care_group == nil %>
      <%= link_to "Request to visit this senior", new_senior_visit_path(@senior), method: :post, class: "waves-effect waves-light btn" %>
    <% end %>
</div>

<div class="row center-align container" style="width: 350px; height: auto; margin-top: 25px">
    <div class="card">
        <div class="card-image">
            <img src="http://i.imgur.com/9JlhmGx.png" style="width: 350px; height: 350px">
        </div>
        <div class="card-content">
            <p>About <%= @senior.name %></p>
        </div>
        <div class="card-action">
            <%= @senior.name %> is interested in <%= @senior.interests %>.
        </div>
    </div>
</div>